### ISSUE TITLE
Noce code change in bfx-api-node-util has broken order creation

### ISSUE THREAD

**Issue by JacobPlaster** [bitfinexcom/bfx-hf-algo#15]
This pulll request https://github.com/bitfinexcom/bfx-api-node-util/commit/9e0d87f4965f518d23b4a55ef7249e95713e6c14 changed the way the nonce is generated.
THe problem is that all of the default order examples use this function to also generate cId when creating an order which is now invalid due to the `* 1000` multiplier

**Comment by robertkowalski** [comment]
fixed
