### ISSUE TITLE
Canceled algo orders from bfx UI, resubmitted after HF service restart

### ISSUE THREAD

**Issue by muradm** [bitfinexcom/bfx-hf-algo#4]
1. Submit accumulate/distribute order.
2. Wait to appear in bfx UI.
3. Cancel from bfx UI.
4. Wait to disappear from bfx UI.
5. See in logs, that order canceled.
6. Wait some arbitrary time.
7. Restart HF service server.
8. Wait to appear same accumulate/distribute order which was canceled on step 3.

**Comment by f3rno** [comment]
@muradm this should be fixed by https://github.com/bitfinexcom/bfx-hf-algo/commit/315b6d93b60fc8373cf953909c6265a947d410ca, can you confirm that it doesn't happen with the latest version (1.0.4)?

**Comment by muradm** [comment]
This case seems to be ok
