### ISSUE TITLE
NPM: Version 1.2.0 not pushed to package manager

### ISSUE THREAD

**Issue by Luehrsen** [bitfinexcom/bfx-hf-algo#9]
After the last bump in version the new version 1.2.0 was apparently not pushed to npm.

https://www.npmjs.com/package/bfx-hf-algo

This creates a conflict in bfx-hf-algo-server, which now depends on version 1.2.0 upon install, which is not available on npm.

**Comment by robertkowalski** [comment]
thanks for the report @Luehrsen -- I see the ticket is quite old, recently latest versions were all published to npm. we are moving fast to create good user experience with focus on stability currently.

our next UI release is scheduled for Wednesday.
